#+BEGIN_SRC restclient
GET http://localhost:3000/greet
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "message": "hello chris"
}
// GET http://localhost:3000/greet
// HTTP/1.1 200 OK
// X-Frame-Options: SAMEORIGIN
// X-XSS-Protection: 1; mode=block
// X-Content-Type-Options: nosniff
// X-Download-Options: noopen
// X-Permitted-Cross-Domain-Policies: none
// Referrer-Policy: strict-origin-when-cross-origin
// Content-Type: application/json; charset=utf-8
// Vary: Accept
// Cache-Control: no-store, must-revalidate, private, max-age=0
// X-Request-Id: a488841a-3897-4e8f-a7d8-9e1526aca4de
// X-Runtime: 0.143775
// X-MiniProfiler-Original-Cache-Control: max-age=0, private, must-revalidate
// X-MiniProfiler-Ids: 7ypiurpf475ncm55d06m,kh9xcg4tf4m0y7bh5k0n,vtx8q1v8k8266fku9fl3,ikvimxjuw08mzg5a3oc5,9ttgdhzeixu7dw84mle,djnf26ej1gcb4zejkd3v,woxqdgg48wd3kfprn0rh,e9qn038aypigqtukdt50,olcz4gjd0k2be4lf4cbb,p1gfeor3nn6tmrfoxprg,ia3lffngl2ix99n95d1j,gj2p254qq45b7hbqjnpq,tkcapi7vdfcho7jrxvg,tfrr7h7w2csp0mfgiyh9,s91cvedifut4y7pjko5f,ckj6d0c1ukjgd9ptrxju,sj9tfdmjphf8fm1j24dp,tbf814r9oeboqxov1oii,s8lyp6saswq4ku43uxdw,3lztb99m67mkremnsoa8
// Set-Cookie: __profilin=p%3Dt; path=/; HttpOnly; SameSite=Lax
// Transfer-Encoding: chunked
// Request duration: 0.605721s
#+END_SRC

#+BEGIN_SRC restclient
	POST http://localhost:3000/create_category

		 
#+END_SRC

#+RESULTS:
#+BEGIN_SRC js
{
  "message": "success11"
}
// POST http://localhost:3000/create_category
// HTTP/1.1 200 OK
// X-Frame-Options: SAMEORIGIN
// X-XSS-Protection: 1; mode=block
// X-Content-Type-Options: nosniff
// X-Download-Options: noopen
// X-Permitted-Cross-Domain-Policies: none
// Referrer-Policy: strict-origin-when-cross-origin
// Content-Type: application/json; charset=utf-8
// Vary: Accept
// Cache-Control: no-store, must-revalidate, private, max-age=0
// X-Request-Id: 4b6920d2-b070-44e7-bd43-dcbb91adeb24
// X-Runtime: 0.044415
// X-MiniProfiler-Original-Cache-Control: max-age=0, private, must-revalidate
// X-MiniProfiler-Ids: im6dnymyvxnmsd6ky6h1,7ypiurpf475ncm55d06m,kh9xcg4tf4m0y7bh5k0n,vtx8q1v8k8266fku9fl3,ikvimxjuw08mzg5a3oc5,9ttgdhzeixu7dw84mle,djnf26ej1gcb4zejkd3v,woxqdgg48wd3kfprn0rh,e9qn038aypigqtukdt50,olcz4gjd0k2be4lf4cbb,p1gfeor3nn6tmrfoxprg,ia3lffngl2ix99n95d1j,gj2p254qq45b7hbqjnpq,tkcapi7vdfcho7jrxvg,tfrr7h7w2csp0mfgiyh9,s91cvedifut4y7pjko5f,ckj6d0c1ukjgd9ptrxju,sj9tfdmjphf8fm1j24dp,tbf814r9oeboqxov1oii,s8lyp6saswq4ku43uxdw
// Set-Cookie: __profilin=p%3Dt; path=/; HttpOnly; SameSite=Lax
// Transfer-Encoding: chunked
// Request duration: 0.047706s
#+END_SRC

